services:
  postgres:
    image: postgres:13
    env_file:
      - config/database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        ollama serve &
        sleep 10
        ollama pull mistral:7b
        wait

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./domain-specific-model-pipeline:/app/domain-specific-model-pipeline
    ports:
      - "4141:4141"
#    environment:
#      - KEDRO_ENV=docker
    command: ["kedro", "viz", "--host", "0.0.0.0"]


volumes:
  postgres_data:
  ollama_data:
